-- AlterTable
ALTER TABLE `appsconfig` ADD COLUMN `lastAbsenceMinutes` INTEGER NOT NULL DEFAULT 17,
    ADD COLUMN `lat` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `long` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `meterTolerance` INTEGER NULL DEFAULT 0;
