-- AlterTable
ALTER TABLE `absence` MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `users` ADD COLUMN `statusPTKP` VARCHAR(191) NOT NULL DEFAULT 'TK';
